export const environment = {
  production: true,
  api: 'https://exteotera.herokuapp.com/',
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbGllbiI6eyJpZCI6MSwibmFtZSI6IlNhbWkiLCJlbWFpbCI6bnVsbCwicm9sZSI6bnVsbCwicGFzc3dvcmQiOiIkMmIkMTMkcEhQc1ZVeExvRmhyMHVOVUNuODRlLkhnRGJKdlN6UmZuT1B6YUt0YzEuZ2tteHczU0EvU2UiLCJ0b2tlbiI6bnVsbH0sImlhdCI6MTY2Mjk3MTczMn0._MMkuf9kEC29NlBq6NCUy0x7-gQiOC8UogRApfXIF6g'
};
