
name: Pipeline

on:
  push:
    branches:
      # semantic-release valid branches, excluding all-contributors
      - '+([0-9])?(.{+([0-9]),x}).x'
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
      - '!all-contributors/**'
  pull_request:
    types: [opened, synchronize]

jobs:
  code_validation:
    name: Code Validation
    runs-on: ubuntu-latest

    steps:
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint code
        run: npm run lint
#
#      - name: Check format
#        run: npm run format:check
